<Project>
    <PropertyGroup>
        <GamePath Condition="'$(GamePath)' == '' And Exists('C:\Program Files (x86)\Steam\steamapps\common\Valheim')">C:\Program Files (x86)\Steam\steamapps\common\Valheim</GamePath>
        <DeployToGame Condition="'$(DeployToGame)' == ''">false</DeployToGame>
    </PropertyGroup>
</Project>
